### ISSUE TITLE
design review

### ISSUE THREAD

**Issue by gkasprow** [elhep/FMC_ADC100M_10B_TDC_16cha#1]
@michalgaska please check
 - [ ]  ADC and TDC power supplies - first is 1.8, second 3.3V
 - [ ] VADJ to 3.3 and 1.8V level converters - make sure the right power supplies are connected
 - [ ] ADC common mode
 - [ ] TDC and ADC clocks connected to FMC clocks, data in same banks
 - [ ] I2C devicess addresses (conflicts) compatibility with AFCK

**Comment by gkasprow** [comment]
- [ ] power supply connector assignment and alignment between the boards
 - [ ] signal assignment on mini SAS connector between FMC and Hub boards
 - [ ] ADC, CLK distribution and TDC SPI - make sure SPI MISO is HiZ when no chip is selected
 - [ ] LVDS and analog signal termination
 - [ ] I2C translators

On PCB:
 - [ ] make sure that fragile analog lines are away from digital ones.

**Comment by gkasprow** [comment]
@wzab please have a look at FPGA signal assignment. Use this release:
https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/releases/tag/v1.0rc1

**Comment by wzab** [comment]
The board should work with AFCK or with AFCZ?

**Comment by gkasprow** [comment]
Afck

**Comment by wzab** [comment]
Basing on the delivered [FMC_TDC_signals.txt](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3294100/FMC_TDC_signals.txt)
 file, I have prepared the better ordered [signals_fixed.txt](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3294101/signals_fixed.txt)
 file (in which the name of the FMC signal always precedes the name of the net).
To analyse correctness of connections I have prepared the script 
[netlist_py.zip](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3294106/netlist_py.zip) that uses the AFCK netlist [pinout_csv.zip](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3294108/pinout_csv.zip).

The list of conenctions is generated for two cases. The board in FMC1 and the board in FMC2.
Thw full list of connections is in [results.txt](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3294109/results.txt), while the list without differential signals is in [results_no_diffs.txt](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3294110/results_no_diffs.txt)

The first file shows that clocks and differential lines are probably connected reasonably (assuming that they are AC-coupled LVDS, and in case of outputs the banks they are connected to are NOT powered from 3.3V).
The second file requires further checking by somebody who knows the attached peripherals if unidirectional signals connected to the same bank use compatible standard (and in case of 3.3V powered banks that there are no LVDS outputs connected to the same bank).
