### ISSUE TITLE
Netlist

### ISSUE THREAD

**Issue by wzab** [elhep/FMC_ADC100M_10B_TDC_16cha#2]
Dear Greg,
Send me please the netlist for FMC connector, so that I could avoid decoding connections from PDF.
BR, Wojtek

**Comment by gkasprow** [comment]
THe connector has FMC-style net naming like LA1, LA2 etc
I can easily generate only signal pairs:
[FMC_TDC_signals.txt](https://github.com/elhep/FMC_ADC100M_10B_TDC_16cha/files/3292093/FMC_TDC_signals.txt)
